#!/usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = 'Steven'

import scrapy


class KodateItem(scrapy.Item):
    _id = scrapy.Field()
    _item_name = scrapy.Field()
    house_no = scrapy.Field()
    house_name = scrapy.Field()
    house_type = scrapy.Field()
    house_price = scrapy.Field()
    house_address = scrapy.Field()
    house_layout = scrapy.Field()
    house_area = scrapy.Field()
    house_transports = scrapy.Field()
    house_imgs = scrapy.Field()
    house_floor = scrapy.Field()
    house_status = scrapy.Field()
    house_equipments = scrapy.Field()
    building_name = scrapy.Field()
    building_date = scrapy.Field()
    building_structure = scrapy.Field()
    building_density = scrapy.Field()
    building_no = scrapy.Field()
    land_area = scrapy.Field()
    land_rent = scrapy.Field()
    land_rights = scrapy.Field()
    land_purpose = scrapy.Field()
    land_terrain = scrapy.Field()
    land_law_record = scrapy.Field()
    # 私道負担面積
    road_area = scrapy.Field()
    # 接道状況
    road_status = scrapy.Field()
    comments = scrapy.Field()
    repairs = scrapy.Field()
    parking = scrapy.Field()
    city_plan = scrapy.Field()
    plot_ratio = scrapy.Field()
    set_back = scrapy.Field()
    bargain = scrapy.Field()
    house_link = scrapy.Field()
    scrawl_time = scrapy.Field(serializer=str)
    info_open_time = scrapy.Field(serializer=str)
    next_update_time = scrapy.Field(serializer=str)


class MansionItem(scrapy.Item):
    _id = scrapy.Field()
    _item_name = scrapy.Field()
    house_no = scrapy.Field()
    house_name = scrapy.Field()
    house_type = scrapy.Field()
    house_price = scrapy.Field()
    unit_price = scrapy.Field()
    house_address = scrapy.Field()
    house_layout = scrapy.Field()
    house_area = scrapy.Field()
    balcony_area = scrapy.Field()
    house_transports = scrapy.Field()
    house_imgs = scrapy.Field()
    house_floor = scrapy.Field()
    house_status = scrapy.Field()
    house_equipments = scrapy.Field()
    house_holds  = scrapy.Field()
    building_name = scrapy.Field()
    building_date = scrapy.Field()
    building_structure = scrapy.Field()
    building_density = scrapy.Field()
    building_no = scrapy.Field()
    land_area = scrapy.Field()
    land_rent = scrapy.Field()
    land_rights = scrapy.Field()
    land_law_record = scrapy.Field()
    comments = scrapy.Field()
    repairs = scrapy.Field()
    manage_fee = scrapy.Field()
    repair_fee = scrapy.Field()
    right_fee = scrapy.Field()
    guarantee_money = scrapy.Field()
    maintain_fee = scrapy.Field()
    other_fee = scrapy.Field()
    parking = scrapy.Field()
    bike_parking = scrapy.Field()
    motor_parking = scrapy.Field()
    pet_abled = scrapy.Field()
    manage_type = scrapy.Field()
    bargain = scrapy.Field()
    conditions  = scrapy.Field()
    house_link = scrapy.Field()
    scrawl_time = scrapy.Field(serializer=str)
    info_open_time = scrapy.Field(serializer=str)
    next_update_time = scrapy.Field(serializer=str)
